name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
          
      - name: Build with Maven
        run: mvn -B package --file pom.xml
        
      - name: Run tests
        run: mvn test
        
      - name: Generate test reports
        run: mvn surefire-report:report
        
      - name: Verificar contenido del directorio de reportes
        run: ls -l target/site/ || echo "No existe target/site/"

      - name: Subir reportes de pruebas
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: target/site/
          if-no-files-found: warn   # Opcional: puedes usar 'warn', 'error' o 'ignore'
          retention-days: 7         # Opcional: ajusta según lo que necesites
          compression-level: 6      # Opcional: valor por defecto
          overwrite: true           # Opcional: sobrescribe si ya existe un artifact con el mismo nombre
          include-hidden-files: false # Opcional: incluye archivos ocultos si lo necesitas