name: Build Docker Image

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    branches: [main]
    types:
      - completed
  workflow_dispatch:

jobs:
  build-and-push-docker:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login a Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      - name: Construir y Publicar imagen Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/telconova-support:latest,${{ secrets.DOCKER_HUB_USERNAME }}/telconova-support:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
